### ISSUE TITLE
weight file after training

### ISSUE THREAD

**Issue by kumarshubh707** [khornlund/severstal-steel-defect-detection#2]
can you share me the weight file after training?

**Comment by khornlund** [comment]
You can download the checkpoints used in the kernel [here](https://www.kaggle.com/khornlund/sever-ensemble-classification/data?scriptVersionId=22207424)

**Comment by kumarshubh707** [comment]
I am still not getting where to give input image in code and how & where
should I expect output. Plz help me as soon as possible.

**Comment by khornlund** [comment]
[download.sh[(https://github.com/khornlund/severstal-steel-defect-detection/blob/master/download.sh) gives an example of the folder structure expected

Then you specify the path to the data directory in the config, like [here](https://github.com/khornlund/severstal-steel-defect-detection/blob/master/experiments/fpn-b5.yml#L29)
